sudo: false
language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pytest

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/galleria.py"
  - export FLASK_DEBUG=1

branches:
  only:
    - master

script:
  - flask test
